import ItemInterface from "@/types/ItemInterface";
import { ITEM_STATE_TYPE } from "@/types/ItemStateType";

const mockItems: ItemInterface[] = [
    // 접이식우산 (6개)
    {
        id: 1,
        name: "접이식우산",
        location: "도서관 1층",
        price: 25000,
        password: "1234",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 2,
        name: "접이식우산",
        location: "학생식당",
        price: 28000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 3,
        name: "접이식우산",
        location: "강의동 A",
        price: 22000,
        password: "5678",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 4,
        name: "접이식우산",
        location: "미정 위치",
        price: 26000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
    {
        id: 5,
        name: "접이식우산",
        location: "기숙사",
        price: 24000,
        password: "9012",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 6,
        name: "접이식우산",
        location: "중앙광장",
        price: 23000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },

    // 장우산 (6개)
    {
        id: 7,
        name: "장우산",
        location: "도서관 1층",
        price: 35000,
        password: "3456",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 8,
        name: "장우산",
        location: "강의동 B",
        price: 32000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 9,
        name: "장우산",
        location: "학생식당",
        price: 38000,
        password: "7890",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 10,
        name: "장우산",
        location: "미정 위치",
        price: 34000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
    {
        id: 11,
        name: "장우산",
        location: "기숙사",
        price: 36000,
        password: "2345",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 12,
        name: "장우산",
        location: "중앙광장",
        price: 33000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },

    // 공학용계산기 (6개)
    {
        id: 13,
        name: "공학용계산기",
        location: "도서관 1층",
        price: 45000,
        password: "4567",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 14,
        name: "공학용계산기",
        location: "강의동 A",
        price: 48000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 15,
        name: "공학용계산기",
        location: "학생식당",
        price: 46000,
        password: "8901",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 16,
        name: "공학용계산기",
        location: "미정 위치",
        price: 47000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
    {
        id: 17,
        name: "공학용계산기",
        location: "기숙사",
        price: 44000,
        password: "3456",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 18,
        name: "공학용계산기",
        location: "강의동 B",
        price: 50000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },

    // 보조배터리 (6개)
    {
        id: 19,
        name: "보조배터리",
        location: "도서관 1층",
        price: 15000,
        password: "5678",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 20,
        name: "보조배터리",
        location: "강의동 A",
        price: 18000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 21,
        name: "보조배터리",
        location: "학생식당",
        price: 16000,
        password: "9012",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 22,
        name: "보조배터리",
        location: "미정 위치",
        price: 17000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
    {
        id: 23,
        name: "보조배터리",
        location: "기숙사",
        price: 14000,
        password: "4567",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 24,
        name: "보조배터리",
        location: "중앙광장",
        price: 19000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },

    // 추가 데이터 (6개 - 위 4개 상품 혼합)
    {
        id: 25,
        name: "접이식우산",
        location: "강의동 B",
        price: 27000,
        password: "6789",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
    {
        id: 26,
        name: "장우산",
        location: "도서관 1층",
        price: 37000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 27,
        name: "공학용계산기",
        location: "학생식당",
        price: 49000,
        password: "0123",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 28,
        name: "보조배터리",
        location: "강의동 A",
        price: 20000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.AFFORD,
    },
    {
        id: 29,
        name: "접이식우산",
        location: "기숙사",
        price: 25500,
        password: "7890",
        deleteReason: null,
        state: ITEM_STATE_TYPE.BORROWED,
    },
    {
        id: 30,
        name: "장우산",
        location: "미정 위치",
        price: 31000,
        password: "0000",
        deleteReason: null,
        state: ITEM_STATE_TYPE.REVIEWING,
    },
];

export default mockItems;
