spring:
    application:
        name: backend
    datasource:
        url: jdbc:mysql://userpath
        username: user-username
        password: yourpassword
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
        root: debug
sms-service:
    api-key: ${API-KEY}
    secret-api-key: ${SECRET-API-KEY}
server:
    error:
        include-message: never
        include-binding-errors: never
        include-stacktrace: never
