spring:
    application:
        name: backend
    datasource:
        url: jdbc:mysql://localhost:3306/inha_item_borrow_service
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
logging:
    level:
        root: debug
app:
    jwt:
        secret-key: 8B73D9C4956669F1C6EC3FECD6CC18B73D9C4956669F1C6EC3FECD6CC1
    cloud:
        aws:
            s3:
                credentials:
                    accessKey: accessKey
                    secretKey: secretKey
                bucket: bucket
                dir:
                    name: path
                region: region
    sms-service:
        api-key: ${API-KEY}
        secret-api-key: ${SECRET-API-KEY}
